### ISSUE TITLE
Implement support for paths and rootDirs from tsconfig.json

### ISSUE THREAD

**Issue by iulianraduat** [iulian-radu-at/find-unused-exports#14]
**Feature request**

Implement support for [paths in tsconfig.json](https://www.typescriptlang.org/tsconfig#paths) and [rootDirs in tsconfig.json](https://www.typescriptlang.org/tsconfig#rootDirs).

**Comment by juni0r** [comment]
@iulian-radu-at That'd pretty awesome. We're making heavy use of path aliases in our projects.

**Comment by iulianraduat** [comment]
Hi @juni0r ,

I try to better understand the use cases where are used paths and rootDirs.

Can you post an example of how are the paths defined in your tsconfig.json file? You can alter the folder names as I am interested to see how you define them.

Thanks,
Iulian

**Comment by juni0r** [comment]
@iulian-radu-at We use path aliases in order to avoid relative paths and ending up in double-dot hell, i.e. `import something from '../../../lib/something'`

Our tsconfig.json looks like this (no `rootDir` specified, so that defaults to `.`):

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "$lib": ["src/lib"],
      "$lib/*": ["src/lib/*"],
      "$i18n": ["src/i18n"],
      "$i18n/*": ["src/i18n/*"],
      "$model": ["src/model"],
      "$model/*": ["src/model/*"]
    }
  }
}
```

**Comment by iulianraduat** [comment]
I avoid this kind of problems by defining only the baseUrl (as ".") without any paths and then all my imports look like
```
import mod from "src/lib/....";
```
In case I need to migrate a project form relative to this kind of "absolute" paths, I use my own extension [Fix relative imports to baseUrl](https://marketplace.visualstudio.com/items?itemName=iulian-radu-at.fix-relative-imports-to-baseurl) in VSCode to automatically convert the imports.

From what I see you can also drop the use of paths as long as you replace all imports from "$paths" with imports from "src/paths". Maybe you make a try and let me know if I am right?

QUESTION:
I see that you have this kind of duplicated entries:
```
"$lib": ["src/lib"],
"$lib/*": ["src/lib/*"],
```
Why do you need to have once without wildcard and once with?

Thanks,
Iulian

**Comment by juni0r** [comment]
Your approach works well as long as you're building sources only and there is one common base dir . Many web projects however rely on build tools like webpack or rollup which not only compile .ts files but other assets as well. They still use `tsconfig.json` for configuring the TS-compiler and thus it needs to know about the aliases.

The path aliases are duplicated in `rollup.config.js` and `tsconfig.json`. It also makes sense to use path aliases for tests and they don't share a common build root with your source files since you don't want them to end up in your build. 

As for the entries with wildcard and without, I was also wondering, but I blindly pasted the config from an article and never questioned it. It might work with either one of them, but I never bothered to try it.

**Comment by kayone** [comment]
This would be great, right now there are way too many false positives (imported using alias that aren't detected). So we can't really use this extension for our project without alias support.

**Comment by iulianraduat** [comment]
Sorry guys, I did not forget you but only did not found the time to try and find a solution for this.
Keep your faith on me 😄

**Comment by iulianraduat** [comment]
Version 1.20.0 implements the support for mapped paths in imports.

Please install it or a later version and check if it works as expected.

Thanks,
Iulian

**Comment by iulianraduat** [comment]
Closed as there was no feedback from the reporter.
